version: "3"
services:
  postgres:
    container_name: server-sessions-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/server-sessions-postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: server-sessions-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/server-sessions-pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge